import type { Metadata } from "next";

import "./globals.css";
import TopBar from "@/components/TopBar";
import NavBar from "@/components/NavBar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased `}
      >
        <TopBar />
        <NavBar />
        {children}
      </body>
    </html>
  );
}
